### ISSUE TITLE
GPL-283 As an SSR I would like a tube rack, tube and plate manifest for long read to allow customers to record data that is useful in the long read pipelines

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#2515]
Primary contact: Liz Cook

Acceptance criteria:
- A customer should be able to download a tube rack, tube or plate manifest for long read samples
- It should have the following additional fields; cost code, number of gb required and number of smrt cells. Any others ...
- If any of the above data it should not prevent the manifes from being uploaded

Additional context:
- currently some of the data is missing from sample manifests even though it is available. This has an effect on downstream processing e.g. without the cost code a pacbio sequencing message will not be sent to the warehouse as it is a required field.

**Comment by KatyTaylor** [comment]
Additional information:

Q. Why is cost code a required field in the Multi-LIMS Warehouse?
A. Not sure.
Carol Scott (NPG) said they don't use cost code. Said that for Illumina, a report used to be generated from MLWH for the Ops managers to cross check the billing for the month. Suggested Karen Oliver uses something similar?
Karen said she gets cost code for her reports from SS or the RT tickets, and doesn't have any reports, Tableau or otherwise, that draw data from the MLWH, and doesn't know of anyone who uses cost code in MLWH. However, mentioned she would like to automate her reports in future.

Q. Is sample / sample metadata the right place to store cost code? (As it would be if we add it to the manifest)
A. It's not perfect, because a sample could be sequenced under multiple cost codes in its lifetime. The most likely reason is if the sample has to be re-sequenced, it gets put under an internal sanger cost code. If the re-sequencing is due to a problem with an Illumina machine fault, it gets charged to Illumina. (~300 re-sequenced Oct 2018-Oct 2019, ~120 re-sequenced Oct 2019-Feb 2020)
However, we could store the main cost code on the sample and then provide the possibility to manually change it in Traction if needed, or they could change it later on reports etc.

Q. Why doesn't this information get put into a submission like with the high throughput stuff?
A. Long read pipelines don't use submissions - Liz has no input at this stage in the process. Long read team handle it all themselves, Karen does the charging etc.

Q. Can we help by putting any extra data that is stored on spreadsheets into SS or elsewhere?
A. Liz showed me several spreadsheets:
1. 'Sequel WGS' - long read team use a Google sheet to track their work, as well as the LIMS. This contains Study and Cost Code among other things.
Liz has been making a 'fake' Pacbio plate from the Stock plate produced by Michelle from Samples Extraction, and entering the barcode into this spreadsheet - but has realised doesn't need to do this because Traction automatically links the Traction barcode and the SS barcode / sample id.
2. 'Work Request' - owned by faculty, passes between faculty and customer - also contains qc extraction info - updated by Michelle in long read team - Liz also checks information on it to see how far along the process jobs are - faculty hoping to replace with database / other product.
3. 'WIP' - Liz's personal spreadsheet for tracking ToL stuff - process here improved greatly by recent reporting work - https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Tree+of+Life+Work+In+Progress+%28WIP%29+Reporting - unclear if we can help with other aspects of it.
4. Long read manifest - faculty make this from their work request sheet.

Q. If a Study has multiple Projects, is it possible to assign one of them as the 'primary' project (e.g. the resequencing ones would not be), and therefore automatically work out the most likely cost code?
A. Possible to legitimately have more than one cost code that is not for above-mentioned resequencing, e.g. if a grant runs out and another awarded within duration of study.

**Comment by KatyTaylor** [comment]
Paused work on this, write up so far here -
https://ssg-confluence.internal.sanger.ac.uk/display/PSD/GPL-283+New+fields+in+long+read+manifests
