### ISSUE TITLE
GPL-412 Create plate and samples through API v2

### ISSUE THREAD

**Issue by pjvv** [sanger/sequencescape#2620]
**User story**
As a dev team we would like an endpoint in API v2 to allow for the creation of plates and samples with their metadata.

**Who the primary contacts are for this story**
Philip

**Acceptance criteria**
To be considered successful the solution must allow:
1. an API v2 endpoint for the creation of plate and samples

**Additional context**

**Comment by JamesGlover** [comment]
Background:
- API V1 achieves this through an asset creation object, which then gets persisted to the database, and provides a bit of an audit trail by recording who performed the action, and when. It also sets relationships and plate ;ownership'. This is just a standard rails object, so could be ported to V2 pretty easily.
- Other option would be by being a bit more restful, and just having a POST to api/v2/plate. This could even use plate creation under the hood if we wished.
- Generally plates get created via a call to PlatePurpose#create! We should probably still try and maintain this, regardless of which option we pick.

**Comment by JamesGlover** [comment]
History: We used to have a V1 endpoint for creating sample manifests via the API. Essentially this was a spreadsheet free way of registering samples and their labware in one go. Gives a bit more control I guess, at the expense of flexibility.

**Comment by emrojo** [comment]
I will go with the POST to api/v2/plate option, the plate and samples need to be created from scratch. 
Proposed list of tasks:
* Create a processor _app/resources/api/v2/plate_processor_ that will define _create_resource_ handle the request an build a factory Plate with the params received by json api, if params are not enough to build a plate it will fail the request. 
* Rename current _app/heron/factories/plate.rb_ to _app/heron/factories/plate_from_rack.rb_ because its name does not describe what it really does and clashes with current proposed plate factory. This will require update all references and tests
* Create a new factory _app/heron/factories/plate.rb_ that will validate the arguments received by request and if valid it will create a plate using the plate purpose and study provided
* Create a new factory _app/heron/factories/sample.rb_ to validate and create samples so it can be used by plate factory (and possibly sample tube in future) **In progress**

**Comment by emrojo** [comment]
```json
{
   "data":{
      "type":"plates",
      "attributes":{
         "barcode":"11111",
         "plate_purpose_uuid":"11111",
         "study_uuid":"11111",
         "wells_content":{
            "A01":{
               "phenotype":"A phenotype"
            },
            "B01":{
               "sample_uuid":"11111"
            }
         }
      }
   }
}
```
