### ISSUE TITLE
GPL-549	BUG: Cherry picking on Hamilton cant pick onto a partial plate

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2776]
GPL-549 | BUG: Cherry picking on Hamilton cant pick onto a partial plate

**Describe the bug**
Lesley S wrote (Monday, 22 June 2020 at 16:50)

We ran the first live cherrypick today on the Hamilton. The pick was split over 2 runs the 1st run with no issues, but on the 2nd pick the bed verification failed. We think this may be due to using the same destination plate barcode twice?

Danni W wrote: (Monday, 22 June 2020 at 17:31)

Batch 76468 – The first pick, this worked no issues.
Batch 76469- The second pick, the showed an invalid bed layout error.
Destination plate : DN630440H

Plan of action agreed in 9;30 standup

1. Andrew and Iraad to explore if issue related to no control on second round of picks
2. Danni W to test if issue affects just Hamilton or also the Tecans

**Comment by andrewsparkes** [comment]
After discussion with Iraad:
Hamilton method on the robot requires a control plate in the picking list currently. It doesn't like the second picking file because it has no control in it (because the controls were picked onto the destination already in the first batch). Iraad had to modify the pick file to add a control pick with zero volume to get it to pick (Hamilton method needs to be changed so controls are optional). 
Controls are optional in Sequencescape cherrypicking code so this should not be the reason for the bed verification failure.
Still investigating.
