### ISSUE TITLE
GPL-561 Sentinal pick all the volume of the +ves 

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2819]
**User story**
GPL-561 | As genomics POs (Emma, Rich C & James) we would like to cherry pick all the volume of the +ves because...
-- | --

**Who are the primary contacts for this story**
Emma G
Rich C
James M
Danni W

**Acceptance criteria**

Token for conversation to have

To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
See section 2.2 : https://ssg-confluence.internal.sanger.ac.uk/x/jqsKBg

**Comment by rl15** [comment]
Fixed vol 35ul

**Comment by JamesGlover** [comment]
Zoom meeting Rich C 24th July 2020 14:00

**Where is the volume information coming from**
Currently the actual volume of the plates is unknown, both inside and outside of the Lims. While it would be possible to perform a volume check to establish this value, operations do not feel it would be worth the additional time and administration costs. As a result, the volume information is not available to determine maximum volume.

** What are the alternatives **
Existing picks, and future picks will be performed with fixed volumes of 35ul. There is existing support in Sequencescape for fixed volume picks.

We proceeded to discuss the behaviour of GPL-558 (https://github.com/sanger/lighthouse-ui/issues/2), GPL-559 (https://github.com/sanger/lighthouse-ui/issues/10) and GPL-574 (#2837) and established that operations and PSD have a shared understanding of what the two stories will deliver. It was clarified that:

1) Megabatches created via GPL-559 could contain plates from multiple boxes, although operations indicated that they may actually avoid this functionality in the first phase, due to difficulties managing multiple boxes when setting up picks. GPL-580 is expected to mitigate this (#2848)

2) Batches created would not be automatically processed through the cherrypicking pipeline itself, but would be available ad unprocessed batches in the pipeline inbox page. These could then be processed in the same manner as existing megabatches.

Following confirmation the the lighthouse batches would be processed through the existing cherrypick pipelines it was confirmed that the existing 'pick by volume' functionality would meet the current needs.

The possibility of fully automating the pipeline was raised by PSD, who indicated that it was possible, but probably a fairly significant undertaking. Operations felt that the current planned delivery would cover their immediate needs, and planning further automation at this stage would be premature.

It was established that no further Lims development work will be needed to meet these requirements.
