### ISSUE TITLE
GPL-604 check (chromium) manifest transactions, to avoid inconstant data

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#2870]
**Description**
check (chromium) manifest transactions, to avoid inconstant data

**Who the primary contacts are for this work**
James G
+ one other interested developer from attendees on 5th
Neil S

**Knowledge or Stake holders**
n/a

**Additional context or information**
Seed issue was through RT [#695176] raised by Nat S.
Raised in stand up on 3rd Aug, agreed to meet on 5th to resolve

From meeting of 5th 

1. Original design there was a constraint cant change tags (confirmed by Nat)

Nat S wrote (Tuesday, 4 August 2020 at 11:06) 

"I have learned from Liz Easthope that the manifest upload for Chromium tags had always had these restrictions with not being able to update tags by reupload and we instead have to use the tag sub page. That is absolutely fine to stick with ...now I know that is the way it has always been and that I have to substitute tags in SS itself."

2. RT originally identifies UX issue (The drop-down is super narrow and unusable) – has been fixed, and in production.
3. Potentially larger issue with manifest transactions? - agreed to raise backlog item to investigate.

**Comment by JamesGlover** [comment]
Brief outline:
1) Chromium tags are handled differently, as four tags get applied to the same well. This occurs in `SequencescapeExcel::SpecialisedField::ChromiumTagWell` which iterates over each tag for the well and calls `tag.multitag!(asset)`
2) The first time multitag is called on a well it will tag the aliquot as normal. However if it is called on a well in which the aliquot is already tagged then it will dup the aliquot, and apply the new tags.
3) In addition to validation checks, tag clashes are also prevented at the database level by a unique index on tag_id, receptacle_id, tag2_id.
4) Manifest processing should be wrapped in a transaction, so any failures should cause it to rollback.

Ah!

It appears I misunderstood the description of the original problem, and the tag clash error was being seen when filling in the tag substitutions page, not on manifest upload. As a result it looks like the manifest re-upload was 'successful' and applied multi-tag, causing the duplication. There was no transaction rolled back, because no exception was raised. 

The following is probably irrelevant, but keeping in other possibilities in case the above is wrong.
Potential issues:
1) We are handling the transaction, and then not re-raising or triggering a rollback. (Although then I'm surprised that we'd be seeing a exception)
2) In addition to the upload that triggered the exception, the manifest was re-uploaded in a manner in which no tag clashes were triggered. This completed successfully, but the repeated calls of multitag would have resulted in additional tagging.
3) I misunderstood the describe
3) We're somehow triggering a commit, and breaking the transaction. (This seems unlikely)

**Comment by JamesGlover** [comment]
Fixing re-upload:
`SequencescapeExcel::SpecialisedField::ChromiumTagWell.update`` should update the tags on the existing aliquots if there are already >1 aliquots in the well.
`SampleManifestExcel::Upload::Processor::Base.update_samples_and_aliquots` should collect the substitution hash of all aliquots associated with the row, not just row.aliquot.

**Comment by JamesGlover** [comment]
https://github.com/sanger/sequencescape/issues/2882 handles fix for core issue.
