### ISSUE TITLE
GPL-615 BUG - Qc report failed with out of memory Error.

### ISSUE THREAD

**Issue by emrojo** [sanger/sequencescape#2877]
**Describe the bug**
Qc report created Thu, 13 Aug 2020 20:28:58 +0100 seems to have failed twice, with out of memory Error.
See journalctl at Aug 14 05:37:46 on Sequencescape worker 0

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by JamesGlover** [comment]
Running locally and seeing the following:
1. N+1 query issue, repeated:
```
 Plate Load (47.6ms)  SELECT  `labware`.* FROM `labware` WHERE `labware`.`sti_type` IN ('Plate', 'PlateTemplate', 'ControlPlate', 'DilutionPlate', 'PicoAssayPlate', 'SequenomQcPlate', 'StripTube', 'WorkingDilutionPlate', 'PicoDilutionPlate', 'GelDilutionPlate') AND `labware`.`id` = 27054045 LIMIT 1
  Barcode Load (48.3ms)  SELECT  `barcodes`.* FROM `barcodes` WHERE `barcodes`.`asset_id` = 27054045 ORDER BY `barcodes`.`id` DESC LIMIT 1
  Map Load (44.4ms)  SELECT  `maps`.* FROM `maps` WHERE `maps`.`id` = 29 LIMIT 1
  Aliquot Load (48.4ms)  SELECT `aliquots`.* FROM `aliquots` WHERE `aliquots`.`receptacle_id` = 29691756 ORDER BY `aliquots`.`tag_id` ASC, `aliquots`.`tag2_id` ASC
  Tag Load (45.7ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = -1 LIMIT 1
```
This can inflate memory. Might be related to some of the location report changes, although I thought we addressed this.
2. We seem to be consistently flagging aliquots as suboptimal. This is because there is no qc data associated with the wells. Not a bug, but does indicate that the wrong report type was probably picked. As aliquots have an after commit callback this does mean they'll be help for the duration of the transaction.
3. A quick glance at the code suggests we're batching the wells for report generation, and the transaction is handled on a per batch basis. This should be the correct behaviour, and means we should only have to deal with 1000 wells at a time. Each batch is held in a separate transaction as well, so after commit callbacks aren't the problem. This suggests:
a. Its not the size of the report that's the problem per-se, but an individual record which is loading an inappropriate amount of data
b. More likely we're accidentally caching information somewhere that persists longer than the batch.
c. Less likely: some funky memory fragmentation issue.

Waiting to see how this batch fares locally. We don't have some of the broadcasting stuff enabled, so that might guide us through. We should definitely fix the N+1 issue though.

**Comment by JamesGlover** [comment]
Saw the memory usage of the ruby process increase, but unfortunately the VPN connection died before things completed. Checking object space in the console afterwards doesn't show any obvious leaks persisting beyond the job itself though. Numbers are a little higher than with a fresh console, but such is the nature of lazy method generation and the like. Certainly not seeing large numbers of unexpected classes (like Aliquots or Plates)

**Comment by JamesGlover** [comment]
Generating a csv showing changes in object space per cycle.

What this means:
ObjectSpace.each_object iterates over every ruby object in memory.
From this we're able to count the number of instances of each class.
We collect this information each cycle, and then spit it out to a csv file.
Should be able to graph the number of objects in memory.

**Comment by JamesGlover** [comment]
Well first attempt didn't work. Tried to get the first report generated after five cycles, but it didn't even get that far before the VPN failed. Trying again with smaller batch size and report every cycle.

Suspicion is the whole delayed job is automatically wrapped in a transaction, causing us to persist the aliquots, and possibly qc decisions.

**Comment by JamesGlover** [comment]
And yep! We have an open transaction wrapping the whole job. Which means objects with after transaction callbacks will be held through the entire job. Going to grab the object space data to confirm

**Comment by JamesGlover** [comment]
So object space showed a consistent climb in the number of aliquots. Interestingly the transaction isn't opened by the delayed job, so next suspicion is the state machine.

I'm going to update its gem first, although don't foresee that solving the problem, but I do know they've adjusted the way the interact with transactions, so it makes sense to avoid treading on any toes.

**Comment by JamesGlover** [comment]
It might be a good time to address #2871 as that will reduce the memory impact of all large transactions considerably. This would still mean bigger jobs took more memory over time, but the rate of inflation would be greatly reduced. Still worth trying to have a transaction per batch though.

**Comment by JamesGlover** [comment]
Eliminated the outermost transaction (which definitely worked), and memory usage shot through the roof. Couldn't even get enough cycles to get meaningful object space metrics. Going to fix the N+1 issues, as that can't be helping.

**Comment by JamesGlover** [comment]
Okay, something a little weird is going on, as I get through the first few cycles fine, and at the beginning of the fifth set of wells, we run into issues. Going to check what the query is actually yielding, as before had issues with joins combining to return a crazy number of results.

Edit: Oh its the VPN again. Seriously?!?!

**Comment by JamesGlover** [comment]
Well query returning expected number of results. So not that....

**Comment by JamesGlover** [comment]
Ugh, so configatron is causing problems, probably due to the behaviour of object space itself.

**Comment by JamesGlover** [comment]
![Screenshot 2020-08-28 at 16 50 50](https://user-images.githubusercontent.com/1283620/91587515-c92b4b00-e94e-11ea-9273-3f784ac236cb.png)
Cool, so once I've fixed up the problem with configatron and object space the profile looks a lot more sensible and things progressed a lot more sensibly.

**Comment by JamesGlover** [comment]
N+1 issues fixed and all looking somewhat better now. Finding the wells themselves is still dirt slow, but the query plan doesn't strike me as anything daft. It mostly seems to be beginning with finding all aliquots in the given study, and filtering from there.
