### ISSUE TITLE
GPL-950 change the default labware in worklist made by SScape for Tecan cherry-picking.  

### ISSUE THREAD

**Issue by rl15** [sanger/sequencescape#3142]
**User story**
As sample management product lead (Danni W) I would like to make a change the default labware in the worklist made by SScape for Tecan cherry-picking.  

**Who are the primary contacts for this story**
Danni W

**Acceptance criteria**

Old labware – “96-TROUGH”
New labware- “Trough 100ml”

**Additional context**
Raised my mail to Rich L on 26th March

**Comment by JamesGlover** [comment]
Think this is the important line:
https://github.com/sanger/sequencescape/blob/8afe7da0a9477f951e0d18bea8e1bcd453f982eb/app/models/robot/generator/tecan.rb#L94

Although several tests also seem to expect it.

If a complete switchover is acceptable, then it should be a simple find-replace.

**Comment by neilsycamore** [comment]
New version of Tecan Scripts attached to RT https://rt.sanger.ac.uk/Ticket/Display.html?id=716700

**Comment by emrojo** [comment]
From checking at the files it changes:
```
A;BUFF;;96-TROUGH;...
```
into this
```
A;BUFF Trough;;Trough 100ml;...
```

**Comment by emrojo** [comment]
UAT testing expected 7th May

**Comment by emrojo** [comment]
UAT delayed to start at the end of week May 11-15

**Comment by emrojo** [comment]
From meeting 18th May:

Clarify the format definition:
  - The new Tecan format will specify the source buffer by row (1 to 8)

How to apply the change:
  - Because the file generation can be changed by robot we will follow this route for deploying this change and have a transition period
  - The new version of Tecan file generation will be applied to just a specific list of robots
  - Decided in the meeting we will apply the new version to just the robot Tecan 1)
  - The old version will be kept in Tecan 4 in case is needed in future

**Comment by emrojo** [comment]
Enabled in production for "Tecan 1" on 22 July 2021 - 16:03
