### ISSUE TITLE
DPL-346 - [BUG] Swapping lanes in batches results in possible warehouse data integrity issue [C=M, V=3]

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3532]
When swapping lanes in batches that only contain 2 lanes/requests the mlwh iseq_flowcell table is updated correctly however if there are more than one move is involved i.e 1<=>4 then the iseq_flowcell table gets out of sync and the positions are wrong.
NB I found saving after each move works.

**To Reproduce**
Find a batch that has 4 different source barcodes (it makes it easier on the eye/brain when checking the table)
Production examples are id: 90442, 90440, 90436, 90433
Edit the batch (RHS)
move position 1 to position 4 and 3 (the old 4) to position 1, check iseq_flowcell table positions compared to Sequencescape
The batch ids are iseq_flowcell.id_flowcell_lims
The batch source barcodes are the iseq_flowcell.id_pool_lims

**Comment by JamesGlover** [comment]
It's a little tricky, as I thought I'd already identified and fixed the issue once, so the bug is very much an unknown and may take a while to track down. I'm hoping fairly small.

**Comment by JamesGlover** [comment]
Oh, and just to add (because I forgot it last time I looked at this) this interface is not only used for lane swaps, but also routinely by the sequencing teams for setting up lane order in the first place. (So Neil's suggestion would have to be in addition to this page, not instead of it - although we could lock down this page after batch release and direct people at the lane-swap page instead.)

Should also be clarified that this page *can* be used for all batches, although given that its pretty much just cherrypicking, fluidigm and sequencing in SS now, I'm not sure what use it would be in the other pipelines. (There are much easier ways for sort requests for cherrypicking)
