### ISSUE TITLE
DPL-340 Cardinal - re-use compound samples [C=M, V=4]

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#3589]
**User story**
As NPG, in cases where the same multiplexed library tube is loaded onto all 4 lanes, I would like the compound sample names to be consistent across the lanes, so that the standard pipeline knows to merge the CRAM files, and the Cell Ranger software treats them as a single sample.

Similarly, if the same combination of samples is re-sequenced, we would like the compound sample to be re-used, rather than a new one created. 

This behaviour is consistent with how normal samples work - if a sample is re-sequenced, it will appear in the MLWH as the same sample (unless it is re-uploaded in a new manifest). However, depending on what stage it is re-worked from, it may have a different library or pool id in the warehouse.

This is important because it's currently causing an issue with NPG's processing in the production Cardinal pipeline. NPG have agreed to work around the issue for now, and process the existing data more manually, but it's not sustainable once the pipeline is going at full capacity.

**Who are the primary contacts for this story**
Katy, James, Marina, Steven L

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] When compound samples are made, a check is done to see if that combination of samples already has an existing compound sample. If so, the existing one is re-used.
- [ ] The relevant code runs in the context of a sequencing request. Make sure there are no issues caused by race conditions due to this running four times in parallel due to the four lanes in a flowcell.

**Additional context**
This came out of this research story - https://github.com/sanger/sequencescape/issues/3586

Once this is implemented, tested and deployed, NPG (Marina & Steven L) should be informed, so that they can stop doing their workaround.

**Comment by mgcam** [comment]
The same multiplexed library tube can be loaded onto 2 or 3 lanes out of 4 or onto 2 out of 2. We have not seen these cases yet, but this might happen.

**Comment by harrietc52** [comment]
Q:  "I would like the compound sample names to be consistent across the lanes". Does consistent mean the exact same name for all compound samples in each lane? How are they currently named? 

Q: Whats the relationship with tube? Does a multiplexed library tube, contain 1 compound sample, which contains many samples?

Q: When are compound samples made? At which stage?

Q: What does "runs in the context of a sequencing request" mean?

Q: Unsure what this means: "Make sure there are no issues caused by race conditions due to this running four times in parallel due to the four lanes in a flowcell."
