### ISSUE TITLE
DPL-652 [BUG] Batch page not showing comments

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3744]
As High Throughput Sequencing (Tris B) after selecting requests I click submit to create a batch however the comments area on the batch page is empty and I have to go clicking via the receptacle to double check comments for each pool.

Any chance ‘All Comments’ could be added to the batch sheets page? – see example  attached below

**RT Ticket Number**
https://rt.sanger.ac.uk/Ticket/Display.html?id=771242

![image001](https://user-images.githubusercontent.com/299768/216959584-598592e3-d938-4e6e-b9e5-83183212325c.jpg)

**Comment by yoldas** [comment]
The Comments column of the table is for the comments on the requests shown in rows. If there is no comment on the request, it is showing None instead of the link to the comments page for that request. 

We have now changed it to show the link always. The link will open the request comments page which will show the related comments as well.

If there is no comment on the request, the link text will read “0 comments”.
However, the comments page for the request might still show other comments on the labware.

If there are some comments on the request, it will show the number of comments.

Screenshot of the updated page in the training environment:

<img width="1264" alt="Screenshot 2023-03-07 at 22 22 11" src="https://user-images.githubusercontent.com/91894/223567113-087db116-c9db-4135-a5dd-850f3ae0783e.png">

Screenshot of the comments page for the request (26153738) in the first row of the table, opened by clicking "0 comments":

<img width="1136" alt="Screenshot 2023-03-07 at 22 24 58" src="https://user-images.githubusercontent.com/91894/223567587-98a23396-dd0b-4de3-83cc-d85269a02bba.png">
