### ISSUE TITLE
DPL-942[BUG] Unable to print Swipecard ID barcode

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3912]
As a memeber of the Sample Prep team (Lynda D) the swipecard ID printing function in Sequencescape is not working on either the Toshiba or Squix printers. https://sequencescape.psd.sanger.ac.uk/profile/1251

Many team members barcodes are fading/don’t work anymore and we have a new starter that can’t even print a barcode currently. This has a big impact on our work. People are either typing in their barcode ID to complete work or potentially using someone else barcode, can this be reviewed asap.

 
Toshiba – The barcode completely changes to a non-human readable
Squix – It makes all the characters uppercase which is not how they are scanned using the tap card readers.

 
Example of what prints:
Correct pass ID - 53a54be5 (Amended from RT)
Toshiba barcode printer - 53+A54+B+E5
Squix barcode printer - 53A54BE5

**RT Ticket Number** [RT788805](https://rt.sanger.ac.uk/Ticket/Display.html?id=788805)

A workaround has been found by using SPrint to print code128 barcodes [(SPrint)](http://172.27.18.239/?labelType=plate_96&printRequest=%7B%22layouts%22%3A%5B%7B%22textFields%22%3A%5B%7B%22fontSize%22%3A2%2C%22font%22%3A%22proportional%22%2C%22rotation%22%3A%22north%22%2C%22value%22%3A%22dw15%22%2C%22x%22%3A%222%22%2C%22y%22%3A%225%22%7D%5D%2C%22barcodeFields%22%3A%5B%7B%22x%22%3A%2234%22%2C%22y%22%3A%221%22%2C%22value%22%3A%2243a84be2%22%2C%22cellWidth%22%3A%220.15%22%2C%22height%22%3A%224%22%2C%22rotation%22%3A%22north%22%2C%22barcodeType%22%3A%22code128%22%7D%5D%7D%5D%7D) however this is less than ideal as it involves using two applications to print a barcode

**Comment by TWJW-SANGER** [comment]
Impact of the bug seems limited if only need to print one barcode per member of staff...

Is there a better way of doing this? Research possible solutions limit to 1/2 day.

**Comment by yoldas** [comment]
At the moment, for Toshiba printers, SS is using the label_template `sqsc_96plate_label_template_code39`. It uses `B` for barcode_type, which is for code39 and it does not support the lower case letters. In order to encode lowercase letters, it prefixes the uppercase letter with a plus character. Interpreting the produced barcode becomes unpredictable. Some barcode readers might decode it correctly. 

Similarly, for Squix printers, SS is using the label_template `sqsc_96plate_label_template_code39.yml.erb` . It uses code39 as barcodeType. However, it uppercases the letter characters. 

Before January 2022, SS used the label template `swipecard_barcode_template`. For Toshiba printers, It uses `9` for barcode_type, which is code128 coding and it supports the lower case letters.  For Squix printers, SS used `swipecard_barcode_template.yml.erb`, which uses code39 coding (I am not sure how it was possible to use lower case letters). The PR [3466](https://github.com/sanger/sequencescape/pull/3466) moved from direct printing to printers to printing from within rails to PMB. However, this unified printing makes the decision of which label template to use based on the printer, hence the label_template for 96 plate is picked.

Tasks:

- [ ] deployment project, change swipecard_barcode_template.yml.erb sprint template to use code128.
- [ ] sequencescape project, enable overriding printer based label_template picking, which should get the template name from the existing config. `configatron.swipecard_pmb_template = 'swipecard_barcode_template'`

**Comment by yoldas** [comment]
Not all commits made it to develop. I created Fix dpl-942 merge #3961 to fix the missing commits.
