### ISSUE TITLE
DPL-936-1 [Sequencescape] As developers we need to upgrade JSON API resources to the latest stable version as the current version is broken and it is preventing us upgrading to the long term supported version of Rails 6.1

### ISSUE THREAD

**Issue by stevieing** [sanger/sequencescape#3950]
**Describe the Housekeeping**
As developers we need to upgrade JSON API resources to the latest stable version as the current version is broken and it is preventing us upgrading to The long term supported version of Rails 6.1

**Blocking issues**
Describe any other issues or tickets that may be blocking this change.

**Additional context**
We are currently running JSON API resources 0.9.0. This is not compatible with Rails 6.1 and breaks all of our V2 endpoints. It has also been patched for our usage and this causes further issues with integration with standard Rails libraries

**Comment by stevieing** [comment]
Link to traction service resources to show how we do preloading to improve performance. https://github.com/sanger/traction-service/tree/develop/app/resources/v1

**Comment by stevieing** [comment]
Tasks left to complete:
- preloading to improve performance
- remove jsonapi-resource-matchers (last after integration suite working)
- review comments spec tests for type
- review plates spec capitalisation issue
- review work orders spec because of source_receptacle relation. Maybe it can be removed?
-

**Comment by yoldas** [comment]
Summary:

I have stopped working on upgrading jsonapi from 0.9.0 to 0.10.7 because 1) it is taking too long and 2) it is a maintenance nightmare. In 2019, there was another attempt to upgrade it from 0.9.0 to 0.9.5 which was not concluded. Every version breaks.

jsonapi 0.9.0 references a discontinued ForceSSL module, which is not even used and prevents Rails 6.1 upgrade.

I have tried an alternative solution, which enables Rails 6.1 upgrade:
- forked jsonapi repo into my GitHub account: https://github.com/yoldas/jsonapi-resources
- created a branch from exactly 0.9.0 tag in the fork: [develop](https://github.com/yoldas/jsonapi-resources/tree/develop)
- removed the offending line: `ActionController::ForceSSL,` : [resource_controller_metal.rb](https://github.com/yoldas/jsonapi-resources/blob/develop/lib/jsonapi/resource_controller_metal.rb) 
- created a Sequencescape branch `freeze-jsonapi-resources`
- updated Sequencescape Gemfile to use jsonapi from the forked branch: 
`gem 'jsonapi-resources', github: 'yoldas/jsonapi-resources', branch: 'develop'`
- executed all tests and integration suite against the branch

The final state of the branch allows starting Rails 6.1 upgrade process.

Next steps:
- Fork jsonapi into sanger space instead of a personal GitHub space shown in the steps above
- Merge Sequencescape`freeze-jsonapi-resources` into Sequencescape `develop`
- Rebase the depfu dependency update [PR](https://github.com/sanger/sequencescape/pull/3892)
- Continue working on [DPL-936-2](https://github.com/sanger/sequencescape/issues/4006) and the PR

This story then can be closed with this workaround.

**Comment by TWJW-SANGER** [comment]
@seenanair Just querying the move of this back to Non-Functional Reqs. Is this intentional, only it was in Closed and Done before?

**Comment by seenanair** [comment]
> @seenanair Just querying the move of this back to Non-Functional Reqs. Is this intentional, only it was in Closed and Done before?

@TWJW-SANGER Sorry Tom, I think I accidentally moved it and was not even aware of it. My apologies.
