### ISSUE TITLE
DPL-1033 Sequencescape API not returning all tag groups

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#3992]
When using the SS api NPG/Tech. admin. have noticed that not all tag group data is retrieved

https://sequencescape.psd.sanger.ac.uk/api/v2/tag_groups

**RT Ticket Number**
https://rt.sanger.ac.uk/Ticket/Display.html?id=794527

tag groups 316 and 317 are mentioned in the RT, these sit in among a group of Bioscan (4 tag) tag groups that are also missing.
Last tag group id in prod is 345 last in the api is 272

**Comment by KatyTaylor** [comment]
2 things:

1. The mentioned tag groups are missing from https://sequencescape.psd.sanger.ac.uk/api/v2/tag_groups because they are on the second page, given by https://sequencescape.psd.sanger.ac.uk/api/v2/tag_groups?page%5Bnumber%5D=2&page%5Bsize%5D=100"

2. Not all tag groups are shown in the output of the API - this is because only those with the flag 'visible' set to true are shown. At time of writing, this means 170 out of 297 are available over the API.

Investigation:
Gathered the ids of tag groups that are present in the output of the API calls (all 2 pages), and queried them in the db:

```
SELECT *
FROM tag_groups 
WHERE id IN (5,6,18,20,27,42,66,87,92,93,95,96,117,125,142,148,149,152,153,154,155,156,157,162,167,177,182,183,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,205,206,207,208,209,210,211,212,213,214,217,218,219,220,222,226,227,228,229,231,232,233,236,237,241,242,243,244,245,246,247,248,249,250,251,253,254,255,256,257,258,259,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345);
```
These all have 'visible' set to 1.

Querying the rest of the tag groups in the db...
```
SELECT *
FROM tag_groups 
WHERE id NOT IN (5,6,18,20,27,42,66,87,92,93,95,96,117,125,142,148,149,152,153,154,155,156,157,162,167,177,182,183,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,205,206,207,208,209,210,211,212,213,214,217,218,219,220,222,226,227,228,229,231,232,233,236,237,241,242,243,244,245,246,247,248,249,250,251,253,254,255,256,257,258,259,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345);
```
These all have 'visible' set to 0.
