### ISSUE TITLE
DPL-936-3 [Sequencescape] Update Rails config defaults to version 6.1

### ISSUE THREAD

**Issue by yoldas** [sanger/sequencescape#4005]
**Describe the Housekeeping**
As developers we need to update Rails configuration defaults from version 5 to version 6.1 to match the defaults that are optimised with Rails version 6.1, for improving performance, enabling new features, avoiding deprecation warnings and potential issues, and maintaining consistency.

**Blocking issues**
DPL-936-2 [Sequencescape] Update Rails version to 6.1

**Additional context**
See [Upgrading Ruby on Rails](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html).
After updating Rails version to 6.1 (DPL-936-2), the application will be running using the old framework defaults. Gradually increment version and enable new features, continually run unit and integration tests, and make necessary code changes.

**Comment by dasunpubudumal** [comment]
**Observations**

1. Zeitwerk invokes Ruby's `camelize` function to infer the class name. For instance, 

```ruby
class Api::AliquotIO < Api::Base
   ....
end
```

is not possible in the file `app/models/api/aliquot_io.rb`, as `"aliquot_io".camelize` returns `AliquotIo` (**not** `AliquotIO`).

**Comment by dasunpubudumal** [comment]
A small observation on Rails 5.0 caching. Consider the RSpec test in [`spec/controllers/npg_actions/assets_controller_spec.rb`](https://github.com/sanger/sequencescape/blob/7bde2c326d5c3a827c167334dc6142649746f89c/spec/controllers/npg_actions/assets_controller_spec.rb#L190).

- The test initially creates a valid sequencing request and a cancelled sequencing request.
- Afterwards, it invokes `/pass_qc_state` endpoint.

The expected result is to have the batch to be in `released` state.

For the batch to be in `released` state, [`app/models/batch.rb:576`](https://github.com/sanger/sequencescape/blob/3acee0a087d04b3f131ecd39fa0135bc5f9b2b88/app/models/batch.rb#L576) must return true. However, in Rails 6.1, `batch.requests` return both `passed` and `cancelled` requests, while Rails 5.0 returns only the `passed` request.

This is because the `cancelled` request **does not** pass validations in [`app/models/batch_request.rb`](https://github.com/sanger/sequencescape/blob/0f530f520eaca08f4d322af142bb8089a020e662/app/models/batch_request.rb) model.  This is because of the [`before_validation`](https://github.com/sanger/sequencescape/blob/0f530f520eaca08f4d322af142bb8089a020e662/app/models/batch_request.rb#L30) callback in `batch_request.rb` mentioned above.

The `before_validation` callback calls `record.batch.batch_requests` for each `batch_request` record before validation. In both Rails 5.0 and 6.1, this invocation **does not** return any value for the call for the first `batch_request` created, which is correct.

However, for the second `batch_request`, Rails 6.1 returns, but 5.0 doesn't. This is because of the caching behaviour.

**Comment by dasunpubudumal** [comment]
This story has been extended with the following stories:

1. #4138 
2. #4139
