### ISSUE TITLE
DPL-936-2 [Sequencescape] Update Rails version to 6.1

### ISSUE THREAD

**Issue by yoldas** [sanger/sequencescape#4006]
**Describe the Housekeeping**
As developers we need to update Rails framework from version 6.0 to version 6.1 to enable receiving dependency and security updates as the support for version 6.0 ended on 1st January 2023.

**Blocking issues**
DPL-936-1 [Sequencescape] As developers we need to upgrade JSON API resources to the latest stable version as the current version is broken and it is preventing us upgrading to the long term supported version of Rails 6.1

**Additional context**
See [Upgrading Ruby on Rails](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html)

Do not upgrade Rails defaults to 6.1. That is for another story.

**Comment by dasunpubudumal** [comment]
**References:** 

1. [FastRuby](https://www.fastruby.io/blog/rails/upgrades/upgrade-rails-from-6-0-to-6-1.html)
2. [RailsDiff](https://railsdiff.org/6.0.3.7/6.1.3.2)

**Comment by dasunpubudumal** [comment]
**Documenting some issues faced**:

`ApplicationHelper` is a partially defined module. It's declared in two places.

1. `ApplicationHelper` module in the traditional helpers path: `app/helpers/application_helper.rb`
2. `ApplicationHelper` module in `lib/informatics/lib/informatics/controller_helper.rb` (even though it's named `controller_helper`, the module is named `AppllicationHelper`  )

It seems this confuses Rails' auto-loading module [Zeitwerk](https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html). 

---

**Suggested Fix**: Renaming `ApplicationHelper` module in `lib/informatics/lib/informatics/controller_helper.rb` to `ControllerHelper` and including it in `ApplicationHelper` module in `app/helpers/application_helper.rb`.

**Comment by dasunpubudumal** [comment]
# Issues Captured [Work In Progress]

### Issues with autoloading

1. Partially declared modules are not resolved by the latest Rails version.

`ApplicationHelper` is a partially defined module. It's declared in two places.

1. `ApplicationHelper` module in the traditional helpers path: `app/helpers/application_helper.rb`
2. `ApplicationHelper` module in `lib/informatics/lib/informatics/controller_helper.rb` (even though it's named `controller_helper`, the module is named `AppllicationHelper` )

It seems this confuses Rails' auto-loading module [Zeitwerk](https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html).

**Suggested Fix**

Renaming `ApplicationHelper` module in `lib/informatics/lib/informatics/controller_helper.rb` to `ControllerHelper` and including it in `ApplicationHelper` module in `app/helpers/application_helper.rb` (Done)

## Issues with Styling/Linting

### RuboCop Issues

There are multiple issues in our code that aren’t compatible with new RuboCop version (`1.57.2` → `1.61.1`). 

There are 100 offences left to be fixed (March 7, 2024)

Almost all them have the fix suggested in the RuboCop message itself.

### Prettier Issues

Running `yarn prettier --write .` returns `Error: nesting of 100 is too deep` in several files. This needs to be fixed.

## RSpec Test Failures

Some of the cucumber test failures (RSpec failures) are due to issues mentioned in the **RuboCop Issues** section (e.g. `to_h` → `to_hash`). So please resolve them before diving into solving RSpec failures.

### New `ActiveModel::Error` class

Please check the official [Upgrade Guide for 6.0 → 6.1 Migration](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activemodel-error-class). This causes a lot of the errors in RSpec tests.

Please check [this PR](https://github.com/rails/rails/pull/32313) as well for more information about this change.

**Comment by dasunpubudumal** [comment]
Successful pipeline run: https://gitlab.internal.sanger.ac.uk/psd/integration-suite/-/pipelines/235142

Please note that we need to fix the SSL issue in health checks within the integration suite. Upon investigation, we figured out that it was an issue with the docker container trying to establish the connection with our services (like `baracoda`, etc.). It is **not** related to the Rails 6.1 upgrade.
