### ISSUE TITLE
DPL-1080 Sequencescape - As PSD we would like to remove the need for an EBI connection when seeding data for tests

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/sequencescape#4011]
**Describe the Housekeeping**
Remove requirement for dynamic connection to EBI URL to fetch countries list when seeding test database. Switch to a fixed file load instead.

**Blocking issues**
None

**Additional context**
Relevant code here:
db/seeds.rb line 36 invoking the rake task lib/tasks/insdc/import_countries.rake

EBI URL: https://www.ebi.ac.uk/ena/browser/api/xml/ERC000011

**Comment by dasunpubudumal** [comment]
Hi @andrewsparkes, the `import` rake job in `db/seeds.rb`, executes two sequential tasks.

1. **Downloads the file from EBI** (`:import`): This is its own `rake` job with namespace `insdc:countries:download`.
2. **Imports the content in the downloaded file as seeds**  (`:download`): Parses the content and imports the downloaded countries into the database.

If we add the file into `data` directory, and remove the `:download` prerequisite in the `import` job, the seeding procedure should pick up the data from the file instead of downloading. If a specific file needs to be downloaded in some case, we can execute the `:download` rake job.

Does this sound alright as the change?

**Comment by andrewsparkes** [comment]
Yes sounds good
