### ISSUE TITLE
Y24-013 [BUG] Sequencescape does not show request metadata fields 

### ISSUE THREAD

**Issue by yoldas** [sanger/sequencescape#4047]
**Describe the bug**
Sequencescape shows Unlabelled field instead of request metadata keys. For example,
- cDNA Prep request in https://uat.sequencescape.psd.sanger.ac.uk/requests/19126986
- Limber PCR Bespoke in Production https://sequencescape.psd.sanger.ac.uk/requests/28159555

**RT Ticket Number**
N/A

**To Reproduce**
Steps to reproduce the behaviour:
This might be occurring in submissions with **sequential multiple request types**. Follow the example links above.

Update: After scRNA donor pooling submission unified request types into one, the issue is still there. The assumption of sequential multiple request types is not correct. https://uat.sequencescape.psd.sanger.ac.uk/requests/19198890

**Expected behaviour**
It should show keys shown in the following query instead.
```
Request.find(19126986).request_metadata.field_infos.map(&:key)
=> 
[:customer_accepts_responsibility,
 :fragment_size_required_from,
 :fragment_size_required_to,
 :gigabases_expected,
 :library_type,
 :pcr_cycles]
```

**Screenshots**

Limber PCR Bespoke request in Production: https://sequencescape.psd.sanger.ac.uk/requests/28159555
![Screenshot 2024-03-06 at 14 42 20](https://github.com/sanger/sequencescape/assets/91894/ba4815cf-8a92-4baa-b03b-46a0bb2b172b)

scRNA Core cDNA Prep request in UAT: https://uat.sequencescape.psd.sanger.ac.uk/requests/19126986
![Screenshot 2024-03-06 at 14 55 33](https://github.com/sanger/sequencescape/assets/91894/d7c67329-f43d-46cd-99f6-0dc1ab866ea4)

**Desktop (please complete the following information):**
N/A

**Additional context**
This was discovered in UAT testing of DPL-913 https://github.com/sanger/sequencescape/issues/3900

**Comment by SHIV5T3R** [comment]
So for now, there's a [PR](https://github.com/sanger/sequencescape/pull/4091) which has a hacky fix for this. In this particular case, the key isn't being returned, so instead of creating a view that joins the key-values (`plain_value()`, it will now just directly join the two. 

As for why it's happening, not a clue. I don't think finding exactly why this is happening will resolve anything because this method is used a lot and seems to be working fine, so this specific instance is just being odd. Not sure if it's worth the time to explore why it's not working though.
