### ISSUE TITLE
Y24-181 - Clean up HiSeq submission templates

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/sequencescape#4189]
**Describe the Housekeeping**
As an SSR, I would like the HiSeq-related submission templates to be removed from the dropdown list when creating a submission, because the HiSeq instruments are no longer in use, and it will make the list easier to use.

This means all the templates which end with the word sequencing needs to be deleted except the ones which have MiSeq, NovaSeq X & NovaSeq 6000. 
HiSeq is no longer used hence specially all the Hi Seq templates should be deleted. 

**Who are the primary contacts for this story**
Siobhan, Liz C.

**Who is the nominated tester for UAT**
Siobhan

**Acceptance criteria**

- [ ] Submission template list accessible from 'Start a Bulk Submission' and 'Start a New Submission' menu options in Sequencescape does not display HiSeq related templates and all other Illumina templates. 
- [ ] Submission template list accessible from 'Generate Template' excel sheet under Bulk Submissions page in Sequencescape does not display HiSeq related templates and all other Illumina templates. 
- [ ] This should also reflect in the excel sheet below.

**Dependencies**
None

**References**
None

**Additional context**

- [_to__20240716_sd31.xlsx](https://github.com/user-attachments/files/16251887/_to__20240716_sd31.xlsx)

- ![image](https://github.com/user-attachments/assets/d112e1ca-6425-48cc-93b8-a111068f293f)

- ![image](https://github.com/user-attachments/assets/327e0dbb-cb0d-471f-9bb0-522c0bed5be0)

- ![image](https://github.com/user-attachments/assets/0bbf408a-703a-465b-a86c-f82605724252)
- 
![image](https://github.com/user-attachments/assets/2d301dca-eba1-4839-9e0d-986261145aea)

**Comment by KatyTaylor** [comment]
Developers:

See 
```
SELECT *
FROM submission_templates 
WHERE name LIKE '%hiseq%';
```

As an option for 'soft deleting', check out the functionality of the `superceded_by_id` column.
See `SUPERCEDED_BY_UNKNOWN_TEMPLATE = -2` in the SubmissionTemplate model.

**Comment by KatyTaylor** [comment]
@SujitDey2022 I made this story without realising it had already been requested by SSRs (RT 801994). Feel free to use it or delete it if it's a duplicate!

**Comment by SujitDey2022** [comment]
All the HiSeq ones can go away (HiSeq X, HiSeq4000, HiSeqv4 and HiSeq2500) as the sequencing platforms have been discontinued.

**Comment by sg32-gif** [comment]
**User story**

Need to remove all unused sequencing platforms from SS submission templates that means apart from Mi Seq, Nova SeqX and Nova Seq6000, all other HiSeq and the remaining needs to be deleted. These will not be used again in the future work.

**Who are the primary contacts for this story**
Siobhan Austin; [slw@sanger.ac.uk](mailto:slw@sanger.ac.uk)

Acceptance criteria

In SS:
Apart from the above three mentioned sequencing machine (Mi Seq, Nova SeqX and Nova Seq6000), there are no other machines used. Hence to avoid more confusion, we delete all other templates.



Additional Reference:

There are currently a huge number of submission templates in SS and there is a risk of the wrong one being selected (especially HiSeqX and NovaSeqX due to the similarity in names).

**Comment by SujitDey2022** [comment]
@sg32-gif I have updated the story for your reference based on the refinement session.
