### ISSUE TITLE
Y24-431 - [BUG] Plate location report fails to show labware retention instructions

### ISSUE THREAD

**Issue by neilsycamore** [sanger/sequencescape#4464]
The plate location report is failing to show the retention instructions even though it is set in the manifest and these are present in the labware view page 
e.g. SQPP-61178-N
![RT812071_labware](https://github.com/user-attachments/assets/74b8208e-d979-4808-86cd-343da0078693)
<img width="1150" alt="RT812071_report" src="https://github.com/user-attachments/assets/bdd8d72e-5df8-4507-91b1-d3943afef80b">

**RT Ticket Number**
[RT812071](https://rt.sanger.ac.uk/Ticket/Display.html?id=812071)

**Additional context**
Run plate location reports from [here](https://sequencescape.psd.sanger.ac.uk/location_reports)

**Comment by andrewsparkes** [comment]
Was a typo in the metadata name used in the labware report, using retention_instructions when should be retention_instruction (no s)

**Comment by andrewsparkes** [comment]
<img width="952" alt="Screenshot 2024-11-07 at 16 09 46" src="https://github.com/user-attachments/assets/254c33c6-136a-441e-a48a-f6abb4195f06">

**Comment by KatyTaylor** [comment]
@andrewsparkes see https://github.com/sanger/sequencescape/issues/4095 - legacy data should have been migrated already. What are you seeing - do you think some were missed?

**Comment by andrewsparkes** [comment]
The bug here was because the data was in the Labware field only (which is correct) but the location report code was ONLY looking for the value in the custom metadata. So not aware of a data issue.
A check needs to be made that everything in code that was expecting the value in custom metadata has been changed to look in labware. Maybe this was the only instance.
